### ISSUE TITLE
Buffer.alloc()

### ISSUE THREAD

**Issue by alexzamfir08** [Creepios/sftp-action#1]
(node:1564) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
Warning: Can't add secret mask for empty string in ##[add-mask] command.
Connection established.
Current working directory: /home/s25
Upload finished.

**Comment by Creepios** [comment]
I noticed your issue, I'll take care of it for the next few days

**Comment by moazam1** [comment]
Having same issue.

**Comment by Creepios** [comment]
There were just old dependencies. Thanks for reporting.
