### ISSUE TITLE
active development 

### ISSUE THREAD

**Issue by ghost** [Creepios/sftp-action#14]
this is more of a question. is this project sftp-action is something will be under development and actively releasing new release because the reason i ask is is been hard to find something like this that actually works.

**Comment by Creepios** [comment]
Hey there! Yes this project is under development and also updated but it is difficult for me to actively invest time in this project at the moment. I myself have relatively little free time at the moment to implement new features myself (pull requests are very welcome!), but bugs and security holes will I of course fix immediately.

So yes, it will be actively maintained and new features will be added over time.
